language: python
python:
  - "3.5"
env:
  - DJANGO=1.10
install:
  - pip install -r requirements.txt
  - pip install pep8 --use-mirrors
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225 src"
script:
  - python setup.py test -v 3
