# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20170306_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='defconfiglist',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
