# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_board_defconfiglist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeenBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitcommit', models.CharField(max_length=128)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_builds', to='monitor.Board')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='seenbuild',
            unique_together=set([('board', 'gitcommit')]),
        ),
    ]
