# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20170307_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='defconfiglist',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
