# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20170307_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastChecked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('kernelciboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Board')),
                ('kernelcijob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.KernelCIJob')),
            ],
        ),
    ]
